# config/packages/nelmio_cors.yaml
nelmio_cors:
    defaults:
        allow_origin: ['*'] # Puedes poner '*' para probar, luego limitamos
        allow_credentials: true
        allow_headers: ['Content-Type', 'Authorization']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE']
        max_age: 3600
    paths:
        '^/api/':
            allow_origin: ['http://www.comoencasa.space']
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE']
            allow_headers: ['Content-Type', 'Authorization']
            max_age: 3600

